회원, 배송지, 판매자 기본 api 개발
ClothingStoreService/clothstar_v1.0 pull request #1
Opened 2024-03-19 11:13 UTC by hjj4060

회원가입, 회원 리스트, 회원 조회 api 개발
배송지 입력, 회원 배송지 리스트 조회 api 개발
판매자 입력, 판매자 조회 api 개발

2024-03-19 14:00 UTC, upswp requested changes
현수님 코드리뷰 남겨봅니다. 첫번째 코드리뷰네요 많이 힘드실텐데 고생 많으셨습니다!

2024-03-19 14:00 UTC, upswp commented on src/main/java/org/store/clothstar/common/domain/Flag.java
> +public enum Flag {
하나의 enum이 다양하게 사용이 되는 부분이 올바르지 않습니다. enum은 하나의 객체 안에 존재해야합니다. 

대표적으로 status와 같은 정보를 enum으로 관리됩니다.

2024-03-19 14:00 UTC, upswp commented on src/main/java/org/store/clothstar/member/controller/AddressController.java
> +	public List<AddressResponse> getAllMemberAddress(@PathVariable Long id) {
@PathVariable을 좀 더 다양하게 사용할 수 있는 부분에 대해서 설명드리겠습니다.

`@PathVariable`은 Spring MVC에서 URI의 일부를 메서드 파라미터로 바인딩하는 데 사용되는 어노테이션입니다. 이를 통해 RESTful 경로에서 각 세그먼트를 직접 메서드의 인자로 전달할 수 있습니다. 예를 들어, 클라이언트가 `/v1/members/1`와 같은 URL로 요청을 보냈을 때, `1`이라는 숫자를 메서드 내의 변수로 직접 사용할 수 있게 해줍니다.

`@PathVariable(name = "memberId") Long id`에서 `@PathVariable` 어노테이션이 하는 일은 다음과 같습니다:

- `name = "memberId"`: URL 경로에서 `{memberId}`라고 명시된 부분을 찾습니다. 이는 경로 변수의 이름을 지정합니다.
- `Long id`: 이 경로 변수의 값을 `Long` 타입의 `id` 파라미터로 전달하고, 메서드 내에서 이 파라미터를 사용할 수 있게 합니다.

즉, 이 구문은 URL 경로에서 `memberId`라는 이름의 부분을 찾아 그 값을 `Long` 타입의 `id` 파라미터로 전달하라는 의미입니다. 이렇게 함으로써, 메서드는 동적으로 변하는 URL 경로의 일부분을 파라미터로써 처리할 수 있게 됩니다.

예를 들어, `/v1/members/42` URL에 대한 요청이 있다면, `@PathVariable(name = "memberId") Long id`는 URL 경로의 `42`를 `Long id`에 바인딩하여 메서드 내에서 사용할 수 있게 해줍니다.

2024-03-19 14:00 UTC, upswp commented on src/main/java/org/store/clothstar/member/controller/MemberController.java
>  	}
Pagination이 적용이 되어야 할 것 으로 판단됩니다.

2024-03-19 14:00 UTC, upswp commented on src/main/java/org/store/clothstar/member/controller/SellerController.java
> +		return sellerService.save(createSellerRequest);
save와 같이 개발 용어로 사용될 수 있는 단어는 피해주십시오. 특히 메서드 , 필드명에 사용되는 부분은 피해햐합니다.

2024-03-19 14:00 UTC, upswp commented on src/main/java/org/store/clothstar/member/controller/SellerController.java
> +	public SellerResponse saveSeller(CreateSellerRequest createSellerRequest) {
@Validated와 @Valid를 구분해서 여기서 Validation 처리가 되면 좋겠습니다. 자세한 사항은 노션에 정리해두겠습니다.

2024-03-19 14:00 UTC, upswp commented on src/main/java/org/store/clothstar/member/dto/CreateAddressRequest.java
> +@Setter
어디에는 Getter, Setter를 사용하시고

2024-03-19 14:00 UTC, upswp commented on src/main/java/org/store/clothstar/member/dto/AddressResponse.java
> +@Getter
어디에는 Getter만 사용하셨습니다.

2024-03-19 14:00 UTC, upswp commented on src/main/java/org/store/clothstar/member/domain/Address.java
> +}
1. **중복 생성자 제거**: `@AllArgsConstructor` 어노테이션과 `@Builder` 패턴이 모두 사용되고 있습니다. `@AllArgsConstructor`로 인해 모든 필드를 포함하는 생성자가 자동으로 생성되지만, 별도의 빌더 패턴을 사용하여 좀 더 명시적인 객체 생성 방법을 제공하고 있습니다. `@AllArgsConstructor`가 필요 없어 보이므로, 이를 제거하고 명시적으로 빌더 패턴만 사용하는 것이 좋겠습니다.
2. **불필요한 초기화 제거**: 클래스 필드는 기본적으로 `null`로 초기화됩니다. 생성자나 빌더를 통해 명시적으로 값이 할당되지 않는 한, 필드 초기화를 별도로 선언할 필요가 없습니다.
3. **`@NoArgsConstructor` 추가 (필요한 경우)**: JPA와 같은 ORM을 사용할 경우, 기본 생성자가 필요할 수 있습니다. 이 경우 `@NoArgsConstructor` 어노테이션을 추가하여 기본 생성자를 생성할 수 있습니다. 이는 선택적인 사항이며, 사용하는 기술 스택에 따라 달라집니다.
4. **필드 접근 방식 일관성 유지**: 모든 필드에 대해 `private` 접근 제한자를 사용하고 있으며, 이는 좋은 실습입니다. 필요한 정보를 외부에 제공하기 위해 `@Getter` 어노테이션을 클래스 레벨에 적용했습니다. 이는 클래스의 캡슐화를 유지하는 데 도움이 됩니다.

리팩토링된 코드는 다음과 같습니다:

```java
import lombok.Builder;
import lombok.Getter;

@Getter
@Builder
public class Address {
	private Long addressId;
	private Long memberId;
	private String receiverNm;
	private String zipNo;
	private String address1;
	private String address2;
	private String telNo;
	private String deliveryReq;
	private Flag defaultFg;

	// JPA나 다른 기술 스택을 사용할 경우, 기본 생성자 추가를 고려하세요.
	// 예: @NoArgsConstructor(access = AccessLevel.PROTECTED)
}
```

이 리팩토링은 코드의 명확성과 유지보수성을 향상시키면서도, 필요한 기능을 유지합니다. `@Builder`를 사용하여 객체의 인스턴스를 생성할 때 더 명확하고 유연한 방법을 제공하며, 필요한 경우 추가적인 설정이나 어노테이션을 쉽게 추가할 수 있습니다.

2024-03-19 14:00 UTC, upswp commented on src/main/java/org/store/clothstar/member/service/MemberService.java
>  	}
메서드 순서는
- Get
- Post
- Put
- Patch
- Delete
를 기준으로 해주십시오

2024-03-23 01:47 UTC, samuelmento requested changes

2024-03-23 01:47 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/member/controller/AddressController.java
> +	public AddressResponse addrSave(CreateAddressRequest createAddressRequest, @PathVariable Long id) {
@RequestBody

2024-03-23 02:00 UTC, samuelmento requested changes
수정 부탁드립니다 ~!

2024-03-23 02:00 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/member/dto/AddressResponse.java
> +	private String address2;
필드명이 변경되면 좋겠습니다.
- 유저가 가질 수 있는 주소가 두개인건지?
- 주소가 두개로 관리가 되어야 하는건지?

그래서 의미를 담은 필드명이 필요합니다.

2024-03-23 02:00 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/member/service/AddressService.java
> +		System.out.println("address = " + address);
log로 찍습니다.

서버에서 System.out.println으로 디버깅하는것은 성능상 이슈를 가져올 수 있습니다. 그 이유에 대해서 리서치 해보시면 좋겠습니다.

log 찍는 습관으로만 형성하시는걸 추천드립니다.

2024-03-24 14:28 UTC, axhtl approved these changes

2024-03-24 14:52 UTC, merged