Feature/order
ClothingStoreService/clothstar_v1.0 pull request #15
Opened 2024-04-03 18:09 UTC by axhtl

- OrderServiceTest 추가
deliveredToConfirmOrder_verify()  
deliveredToConfirmOrder_success() >> 진행중
deliveredToConfirmOrder_fail()  >> globalException 적용 안 함
- OrderTest 추가
- CreateOrderRequestTest 추가

2024-04-04 00:41 UTC, samuelmento requested changes
고생하셨습니다 ! 요청드린 부분 수정 부탁드려요!

2024-04-04 00:41 UTC, samuelmento commented on src/main/java/org/store/clothstar/order/orderREADME.md
> +  주문 승인: PATCH /v1/seller/orders/{orderId}-approve
API를 하나로 합쳐주세요!

2024-04-04 00:41 UTC, samuelmento commented on src/main/java/org/store/clothstar/order/dto/CreateOrderRequest.java
> +			.totalPaymentPrice(53000)
이 부분에 대해서 비즈니스 로직을 세워서 외부에서 값을 받아서 객체를 생성할 수 있도록 변경해주세요!

2024-04-04 00:41 UTC, samuelmento commented on src/main/java/org/store/clothstar/order/service/OrderService.java
> +			throw new IllegalStateException("주문 상태가 DELIVERED가 아니므로 CONFIRM으로 변경할 수 없습니다.");
BadRequest로 변경해보면 어떨까요?

2024-04-04 00:41 UTC, samuelmento commented on src/test/java/org/store/clothstar/order/domain/OrderTest.java
> +	void toDto() {
toDTO라고 적기보다는 명확하게 어떤 DTO로 변경하는 테스트 인지 적어주면 나중에 좀더 편하게 추가로 늘릴때 편합니다

2024-04-04 00:41 UTC, samuelmento commented on src/test/java/org/store/clothstar/order/service/OrderServiceTest.java
> +		});
메세지까지도 테스트 코드에 작성해 볼 수 있습니다 ! 그 내용도 추가해보시죠!

2024-04-05 12:00 UTC, Ogu1208 approved these changes

2024-04-07 11:31 UTC, samuelmento approved these changes
승인!

2024-04-07 11:31 UTC, merged