Product 기본 api 개발
ClothingStoreService/clothstar_v1.0 pull request #2
Opened 2024-03-20 15:11 UTC by Ogu1208

Product 생성, 단건 조회 api 개발

2024-03-21 12:06 UTC, samuelmento requested changes
고생많으셨습니다! 확인부탁드릴게요!

2024-03-21 12:06 UTC, dev-mentoring commented on hs_err_pid105020.log
> +vm_info: OpenJDK 64-Bit Server VM (17.0.5+1-b653.25) for windows-amd64 JRE (17.0.5+1-b653.25), built on 2023-01-04 by "builduser" with MS VC++ 16.10 / 16.11 (VS2019)
gitIgnore 쓰시면 해당부분 적용을 안할 수 있습니다! 찾아보시면 좋을 것 같아요!

2024-03-21 12:06 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/product/controller/ProductController.java
> +    private final ProductService productService;
의존성 주입 방식에 다양한 방법이 있습니다. 생성자, 속성 등을 이용한 방법과 @Autowired 부분과 같이 스프링 지원을 통해 의존성 주입을 하는 방법이 있습니다. 

중요한건 규칙성이라 각각의 차이를 먼저 파악하시고 어떤것으로 팀차원에서 할지 정해본다면 규칙적인 코드가 생성될 수 있습니다.

2024-03-21 12:06 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/product/controller/ProductController.java
> +    public CreateProductResponse saveProduct(CreateProductRequest createProductRequest){
음 전에 저희 전에 프로젝트할때 @Valid, @Validated 말씀드렸던걸로 기억하는데요! : )

2024-03-21 12:06 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/product/controller/ProductController.java
> +    public CreateProductResponse saveProduct(CreateProductRequest createProductRequest){
@ResponseBody 누락된것같습니다. 노션에 자세한 사항 정리해둘게요!

2024-03-21 12:06 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/product/controller/ProductController.java
> +        return productService.saveProduct(createProductRequest);
save보다는 create와 같은 표현으로 작성해보면 좋을 것 같습니다.

2024-03-21 12:06 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/product/domain/type/ProductStatus.java
> +    private final String description;
description이 들어가는 이유는 혹시 어떤것때문일까요?

2024-03-21 12:06 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/product/service/ProductService.java
> +    }
```java


    public List<ProductListResponse> getAllProduct() {
        return productRepository.selectAllProductsNotDeleted().stream()
                                .map(ProductListResponse::from)
                                .collect(Collectors.toList());
    }

    public ProductDetailResponse getProduct(Long productId) {
        Product product = productRepository.selectByProductId(productId);
        return ProductDetailResponse.from(product);
    }

    public CreateProductResponse saveProduct(CreateProductRequest createProductRequest) {
        Product product = createProductRequest.toProduct();
        productRepository.save(product);
        return CreateProductResponse.from(product);
    }


```

2024-03-21 12:06 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/product/service/ProductService.java
> +    }
map을 적극적으로 사용하면 코드의 가독성이 향상됩니다!

2024-03-21 12:19 UTC, samuelmento requested changes
내용 추가해봤습니다!

2024-03-21 12:19 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/product/service/ProductService.java
> +        List<ProductListResponse> productResponses = new ArrayList<>();
ProductResponse가 조금 더 좋은 표현으로 생각이 듭니다!

2024-03-24 15:13 UTC, Ogu1208 commented
Product-Create 기본 구현 완료

2024-03-24 15:14 UTC, Ogu1208 commented
Product-Create 기본 구현 완료

2024-03-24 15:15 UTC, hjj4060 approved these changes

2024-03-24 15:29 UTC, merged