feat: access토큰 갱신
ClothingStoreService/clothstar_v1.0 pull request #27
Opened 2024-04-11 12:47 UTC by hjj4060

refresh 토큰으로 access 토큰 갱신기능 개발

2024-04-11 14:29 UTC, samuelmento requested changes
고생하셨습니다! 수정 부탁드릴게요!

2024-04-11 14:29 UTC, samuelmento commented on src/main/java/org/store/clothstar/common/config/jwt/JwtAuthenticationFilter.java
>  		filterChain.doFilter(request, response);
```java
@Override
protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
        throws ServletException, IOException {
    log.info("doFilterInternal() 실행");
    String token = jwtUtil.resolveToken(request);

    // 토큰이 존재하지 않거나 유효하지 않은 경우의 처리
    if (token == null) {
        log.info("JWT 토큰정보가 없습니다.");
    } else if (!jwtUtil.validateToken(token)) {
        log.info("JWT 토큰이 만료되거나 잘못되었습니다.");
        response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
    } else {
        // 토큰이 유효한 경우, 사용자 인증 처리
        authenticateUserWithToken(token);
    }

    filterChain.doFilter(request, response);
}

private void authenticateUserWithToken(String token) {
    Long memberId = jwtUtil.getMemberId(token);
    log.info("memberId: {}", memberId);

    Member member = memberRepository.findById(memberId).orElse(null);
    if (member == null) {
        log.info("해당 memberId의 사용자를 찾을 수 없습니다.");
        return;
    }

    log.info("권한: {}", member.getAuthorities());
    UsernamePasswordAuthenticationToken authToken = new UsernamePasswordAuthenticationToken(member, null, member.getAuthorities());
    SecurityContextHolder.getContext().setAuthentication(authToken);
}
```

리팩토링의 주요 변경 사항은 다음과 같습니다:

1. **중복 코드 제거:** 토큰 유효성 검사와 관련된 로직을 단순화하여 코드의 중복을 줄였습니다. 이제, 토큰이 없거나 유효하지 않은 경우, 각각 로그를 남기고 필요한 경우 401 Unauthorized 상태를 설정합니다.

2. **메소드 추출:** 사용자 인증 로직을 `authenticateUserWithToken`라는 별도의 메소드로 분리하여, `doFilterInternal` 메소드의 복잡성을 줄였습니다. 이로 인해 `doFilterInternal` 메소드가 더 간결해지고, 로직의 개별 부분이 명확하게 구분됩니다.

3. **옵셔널 처리:** `findById` 메소드의 결과를 처리할 때, Java 8의 `Optional`을 사용하여 사용자 객체의 존재 여부를 명확하게 처리합니다. 이는 잠재적인 `NullPointerException`을 방지합니다.

2024-04-11 14:29 UTC, samuelmento commented on src/main/java/org/store/clothstar/common/config/jwt/JwtController.java
> +	}
```java
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;
import org.store.clothstar.common.dto.AccessTokenResponse;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;

@RestController
@RequiredArgsConstructor
@Slf4j
public class JwtController {
    private final JwtUtil jwtUtil;
    private final JwtService jwtService;

    @PostMapping("/v1/access")
    public ResponseEntity<AccessTokenResponse> reissue(HttpServletRequest request, HttpServletResponse response) {
        log.info("access 토큰 refresh 요청");
        String refreshToken = jwtService.getRefreshToken(request);

        if (refreshToken == null) {
            log.info("refresh 토큰이 없습니다.");
            return createErrorResponse("refresh 토큰이 없습니다.", HttpStatus.BAD_REQUEST);
        }

        if (!jwtUtil.validateToken(refreshToken)) {
            log.info("refresh 토큰이 만료되었거나 유효하지 않습니다.");
            return createErrorResponse("refresh 토큰이 만료되었거나 유효하지 않습니다.", HttpStatus.BAD_REQUEST);
        }

        String accessToken = jwtService.getAccessTokenByRefreshToken(refreshToken);
        response.addHeader("Authorization", "Bearer " + accessToken);
        log.info("access 토큰이 갱신 되었습니다.");

        AccessTokenResponse accessTokenResponse = AccessTokenResponse.builder()
                .accessToken(accessToken)
                .message("access 토큰이 생성 되었습니다.")
                .success(true)
                .build();

        return ResponseEntity.ok(accessTokenResponse);
    }

    private ResponseEntity<AccessTokenResponse> createErrorResponse(String message, HttpStatus status) {
        AccessTokenResponse accessTokenResponse = AccessTokenResponse.builder()
                .accessToken(null)
                .message(message)
                .success(false)
                .build();
        return new ResponseEntity<>(accessTokenResponse, status);
    }
}
```

리팩토링에 포함된 주요 변경 사항은 다음과 같습니다:

1. **`createErrorResponse` 메소드 추가**: 에러 응답을 생성하는 로직이 중복되어 있으므로, 이를 별도의 메소드로 분리하여 코드의 중복을 줄이고, 에러 응답을 생성하는 과정의 가독성을 높였습니다.

2. **명확한 HTTP 상태 코드 사용**: `ResponseEntity`를 반환할 때, `HttpStatus.OK`와 `HttpStatus.BAD_REQUEST`를 명시적으로 사용하여 의미를 명확하게 했습니다. 이를 통해 성공적인 응답과 에러 응답을 더 명확하게 구분할 수 있습니다.

3. **로깅 개선**: 각 상황별로 로그를 남기는 것은 그대로 유지하되, 로그 메시지를 통해 프로세스의 어떤 단계에서 어떤 일이 발생했는지 더 명확히 파악할 수 있도록 했습니다.

2024-04-11 14:29 UTC, samuelmento commented on src/main/java/org/store/clothstar/common/config/jwt/JwtService.java
> +}
```java
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import java.util.Arrays;

@Service
@Slf4j
@RequiredArgsConstructor
public class JwtService {
    private final JwtUtil jwtUtil;
    private final MemberRepository memberRepository;

    public String getRefreshToken(HttpServletRequest request) {
        if (request.getCookies() == null) {
            return null;
        }

        return Arrays.stream(request.getCookies())
                .filter(cookie -> "refreshToken".equals(cookie.getName()))
                .findFirst()
                .map(Cookie::getValue)
                .orElse(null);
    }

    public String getAccessTokenByRefreshToken(String refreshToken) {
        return jwtUtil.getMemberId(refreshToken)
                .flatMap(memberId -> memberRepository.findById(memberId))
                .map(member -> {
                    log.info("Creating access token for member: {}", member.getId());
                    return jwtUtil.createAccessToken(member);
                })
                .orElse(null);
    }
}
```

리팩토링의 주요 변경 사항은 다음과 같습니다:

1. **람다 표현식과 스트림 API 사용:** `getRefreshToken` 메소드에서는 `Arrays.stream()`을 사용하여 쿠키 배열을 스트림으로 변환하고, `filter()` 메소드로 "refreshToken" 이름의 쿠키를 찾은 다음, `findFirst()`로 첫 번째 일치하는 쿠키를 찾습니다. 만약 존재한다면, `map()`을 통해 쿠키의 값을 가져오고, 그렇지 않으면 `orElse(null)`을 통해 `null`을 반환합니다.

2. **`Optional` 사용:** `getAccessTokenByRefreshToken` 메소드에서는 `jwtUtil.getMemberId(refreshToken)`의 결과로 `Optional<Long>`를 반환하고, `flatMap()`을 사용하여 `memberRepository.findById(memberId)`의 결과인 `Optional<Member>`를 직접 처리합니다. 만약 `Member` 객체가 존재한다면, `map()`을 사용하여 액세스 토큰을 생성합니다. 이 과정에서 `Member` 객체가 존재하지 않으면 `orElse(null)`을 통해 `null`을 반환합니다.

2024-04-12 14:44 UTC, axhtl approved these changes

2024-04-12 14:45 UTC, merged