orderline 기본 api 개발
ClothingStoreService/clothstar_v1.0 pull request #3
Opened 2024-03-20 22:02 UTC by axhtl

orderline 생성, 조회 기본 api 개발

2024-03-20 23:57 UTC, samuelmento requested changes
고생많으셨습니다! 수정사항 반영해서 업데이트 부탁드립니다!

2024-03-20 23:57 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/controller/OrderController.java
> +	public CreateOrderRequest saveOrder(CreateOrderRequest createOrderRequest) {
값을 저장하는 로직 -> Post

- @ RequestBody 로 값을 받기  
```
@RequestBody CreateOderRequest
```

@RequestParam
@Pathvariable

수빈님께서 찾아보셔야 하는 내용은 위와같이 통신 방법에서 값을 전달받을 수 있는 방법들에 대해서 학습해보시고 차이점을 찾아보시면 좋습니다!

2024-03-20 23:57 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/dto/CreateOrderRequest.java
> +@Setter
@RequestBody를 사용하게되면 @Setter를 사용하지 않으셔도 됩니다!

2024-03-20 23:57 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/controller/OrderController.java
> +		return orderService.saveOrder(createOrderRequest);
@Setter를 사용하게 될 경우,
createOrderRequest.shipingAmt = 10;
값을 변경이 가능합니다.

2024-03-20 23:57 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/controller/OrderController.java
> +	public CreateOrderRequest saveOrder(CreateOrderRequest createOrderRequest) {
@Valid, @Valided 가 있는데 내용은 노션에 작성해둘게요!

2024-03-20 23:57 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/domain/Order.java
> +	@DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
이 어노테이션은 컨트롤러의 DTO에서 값을 포맷팅해서 가져오면 더 좋습니다!

2024-03-20 23:57 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/dto/OrderResponse.java
> +@Setter
Setter가 어디에 들어가고 안들어갈지 전략을 다시 세우시면 좋겠습니다!

2024-03-20 23:57 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/service/OrderService.java
> +	}
각 메서드 나열방식에서 Get, Post, Put, Patch, Delete와 같이 순서가 일정하게 반영되면 좋습니다

2024-03-20 23:57 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/service/OrderService.java
> +		orderRepository.saveOrder(createOrderRequest);
CreateOrderRequest는 DTO -> 데이터를 옮기는 역할을 합니다.
값을 저장하고 있는 역할까지도 하고 있습니다.

CreateOrderRequestDTO가 Order 객체로 변환한 상태에서 Repository에 저장이 되어야 합니다.

2024-03-20 23:57 UTC, samuelmento commented on src/main/java/org/store/clothstar/order/service/OrderService.java
> +		orderRepository.saveOrder(createOrderRequest);
Order 객체 name 필드가 있다고 가정해보겠습니다.

OrderRequest에도 name 필드가 있습니다.

Order가 저장이 될때는 OrderRequest.name + 현재시간의 양식으로 들어가야합니다.

이럴때 저희는 외부에서 받아온 OrderRequest DTO를 가공하여 Order를 저장해야합니다.

2024-03-20 23:57 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/service/OrderService.java
> +		return orderResponse;
Order를 그대로 던지지 않고 OrderResponse의 객체로 던지는 부분은 잘하셨습니다.

OrderResponse는 여기서 생성을 하면 안됩니다.

Order의 메서드로 만들어 줘야합니다.

2024-03-20 23:57 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/domain/Order.java
> +}
```
public OrderResponse toResponseDTO(Long orderId, Long memberId, Long deliveryId, String createdDt,LocalDateTime createdAt, String status,int shippingAmt, int productsAmt, PaymentMethod paymentMethod, int paymentAmt) {

    return new OrderResposne (
...
)
```

2024-03-20 23:57 UTC, samuelmento commented on src/main/java/org/store/clothstar/order/service/OrderService.java
> +			order.getDeliveryId(), order.getCreatedDt(), order.getCreatedAt(), order.getStatus(),
축약어 사용하지마시고 다 작성부탁드립니다!

2024-03-20 23:57 UTC, samuelmento commented on src/main/resources/mappers/Order.xml
> +    <!--    </select>-->
필요없는 코드는 삭제부탁드립니다!

2024-03-20 23:57 UTC, samuelmento commented on src/main/java/org/store/clothstar/order/service/OrderService.java
> +			order.getProductsAmt(), order.getPaymentMethod(), order.getPaymentAmt());
new OrderResponse (
  orderId = order.getOrderId(),
  meberId = order.getMemberId(),
// memberId는 OrderResponse의 필드 이름으로 가정합니다.

2024-03-20 23:57 UTC, samuelmento commented on src/main/resources/sql/order.sql
> +VALUES ('1', '2', '3', 'a', now(), 'b', '4', '5', '6', '7');
테스트 데이터는 실 데이터와 최대한 동일하게 값을 넣어주셔야 좋습니다!

2024-03-24 12:58 UTC, samuelmento approved these changes
고생하셨습니다!!

2024-03-24 14:18 UTC, hjj4060 approved these changes

2024-03-24 14:21 UTC, merged