Feature/order create
ClothingStoreService/clothstar_v1.0 pull request #5
Opened 2024-03-27 11:02 UTC by axhtl

통합테스트 OrderIntegrationTest는 만들고 있는 중입니다.

2024-03-27 23:04 UTC, samuelmento requested changes
고생하셨습니다 ~! 코드 수정 부탁드릴게요!

2024-03-27 23:04 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/dto/CreateOrderRequest.java
> +			.status(Status.APPROVE)
여기서 status가 APPROVE가 올바른 초기화일지 궁금합니다.

2024-03-27 23:04 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/dto/CreateOrderResponse.java
> +}
1. **생성자 대신 `@AllArgsConstructor` 사용**: 모든 필드를 초기화하는 생성자를 제공하는 대신, Lombok의 `@AllArgsConstructor` 애너테이션을 사용하여 자동으로 생성자를 생성할 수 있습니다. 이는 코드를 더 깔끔하게 만들어 줍니다.

2. **필드 접근 제어자 명시**: `createdAt` 필드에 접근 제어자가 명시되어 있지 않습니다. 일관성을 위해 `private` 접근 제어자를 추가하는 것이 좋습니다.

3. **클래스와 필드에 대한 문서화 주석 추가**: 코드의 유지보수성을 높이기 위해 클래스와 주요 필드에 대한 간단한 문서화 주석을 추가하는 것이 좋습니다. 이는 나중에 코드를 읽는 사람이 코드의 목적을 더 쉽게 이해할 수 있도록 돕습니다.

리팩토링된 코드 예시는 다음과 같습니다:

```java
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import java.time.LocalDateTime;

/**
 * 주문 생성 응답을 나타내는 클래스입니다.
 */
@Getter
@Builder
@AllArgsConstructor
public class CreateOrderResponse {
	private Long orderId;
	private Long memberId;
	private Long addressId;
	private LocalDateTime createdAt; // 주문 생성 시간
	private Status status; // 주문 상태
	private int totalShippingPrice; // 배송비 총액
	private int totalProductsPrice; // 상품 가격 총액
	private PaymentMethod paymentMethod; // 결제 방법
	private int totalPaymentPrice; // 최종 결제 금액

	// 필드에 대한 추가적인 설명이나 로직이 필요한 경우, 여기에 메소드를 추가할 수 있습니다.
}
```

2024-03-27 23:04 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/utils/GenerateOrderId.java
> +}
```java
import java.security.SecureRandom;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class GenerateOrderId {

    private static final String DATE_FORMAT = "yyyyMMdd";
    private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern(DATE_FORMAT);
    private static final int RANDOM_NUMBER_LENGTH = 7;
    private static final SecureRandom SECURE_RANDOM = new SecureRandom();

    /**
     * Generates a unique order ID based on the current date and a random number.
     *
     * @return Unique order ID as Long
     */
    public static Long generateOrderId() {
        String datePrefix = getDatePrefix();
        String randomDigits = generateRandomDigits();
        return Long.parseLong(datePrefix + randomDigits);
    }

    /**
     * Gets the current date as a string in the specified format.
     *
     * @return Current date as string
     */
    private static String getDatePrefix() {
        return LocalDate.now().format(DATE_TIME_FORMATTER);
    }

    /**
     * Generates a string of random digits of specified length.
     *
     * @return String of random digits
     */
    private static String generateRandomDigits() {
        return IntStream.range(0, RANDOM_NUMBER_LENGTH)
                        .mapToObj(i -> String.valueOf(SECURE_RANDOM.nextInt(10)))
                        .collect(Collectors.joining());
    }
}
```

2024-03-27 23:04 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/order/utils/GenerateOrderId.java
> +}
코드 간결성: for 루프 대신 IntStream을 사용하여 무작위 숫자 생성 부분을 더 간결하게 만들 수 있습니다.
메서드 분리: 주문 ID를 구성하는 두 부분(날짜 접두사와 무작위 숫자)을 생성하는 로직을 별도의 메서드로 분리하여 각 부분의 생성 로직을 더 명확하게 할 수 있습니다.
성능 개선: 매번 DateTimeFormatter를 생성하는 대신, 이를 상수로 선언하여 재사용할 수 있습니다. 이는 성능을 약간이나마 향상시킬 수 있습니다. ( DateTimeFormatter 를 기존방식대로 사용하셔도 됩니다. 😉)

2024-03-27 23:04 UTC, samuelmento commented on src/test/java/org/store/clothstar/order/controller/OrderIntegrationTest.java
> +}
오 테스트 코드가 많이 늘었군요!

2024-03-29 14:44 UTC, hjj4060 approved these changes

2024-03-29 14:45 UTC, merged