Feature/product category
ClothingStoreService/clothstar_v1.0 pull request #7
Opened 2024-03-29 15:16 UTC by Ogu1208

Product로직 수정, Category 로직, Option 로직 구현

2024-03-30 01:34 UTC, samuelmento requested changes
이 부분 수정 부탁드려요!

2024-03-30 01:34 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/category/controller/CategoryController.java
> +    }
### 기존 코드 리뷰

- **URL 설계**: `/v1/categories`는 버전을 명시하고 있어서 좋으며, 리소스를 나타내는 `categories`를 사용하여 적절한 RESTful 설계를 보여줍니다.
- **HTTP 메서드 사용**: `GET`과 `POST` 메서드를 적절히 사용하여 리소스의 조회와 생성 기능을 구현하고 있습니다.
- **상태 코드 사용**: `200 OK`와 `201 Created`를 적절히 반환하여 HTTP 응답 상태 코드를 잘 활용하고 있습니다.

### 코드 변경 제안

변경할 주요 부분은 코드의 RESTful성을 높이기 위한 세밀한 조정입니다. 특히, 생성된 리소스에 대한 정확한 위치를 `Location` 헤더를 통해 반환하는 것이 RESTful API 설계의 좋은 실습입니다.

```java
@RestController
@RequiredArgsConstructor
@RequestMapping("/v1/categories")
public class CategoryController {

    private final CategoryService categoryService;

    @Operation(summary = "전체 카테고리 조회", description = "모든 카테고리를 조회한다.")
    @GetMapping
    public ResponseEntity<List<CategoryResponse>> getAllCategories() {
        List<CategoryResponse> categoryResponses = categoryService.getAllCategories();
        return ResponseEntity.ok().body(categoryResponses);
    }

    @Operation(summary = "카테고리 등록", description = "카테고리 타입(이름)을 입력하여 신규 카테고리를 등록한다.")
    @PostMapping
    public ResponseEntity<Void> createCategory(@Validated @RequestBody CreateCategoryRequest createCategoryRequest) {
        Long categoryId = categoryService.createCategory(createCategoryRequest);
        URI location = ServletUriComponentsBuilder
            .fromCurrentRequest() // 현재 요청의 URI를 사용
            .path("/{id}") // 경로 변수 추가
            .buildAndExpand(categoryId) // {id} 자리에 실제 categoryId 값을 삽입
            .toUri(); // 최종 URI 생성
        return ResponseEntity.created(location).build();
    }
}
```

### 변경한 코드 설명

- **`createCategory` 메서드의 반환 타입 변경**: 생성된 리소스의 ID만을 반환하는 대신, `ResponseEntity<Void>`를 사용하여 응답 본문 없이 상태 코드와 헤더만 반환하도록 변경했습니다. 이는 RESTful API에서 리소스 생성 시 일반적인 방법입니다.
- **`Location` 헤더 설정**: `ResponseEntity.created()` 메서드에 `URI` 객체를 전달하여 생성된 리소스의 위치를 `Location` 헤더에 정확히 명시했습니다. 이를 위해 `ServletUriComponentsBuilder`를 사용하여 현재 요청의 URI를 기반으로 새 리소스의 위치를 동적으로 생성합니다.

2024-03-30 01:34 UTC, dev-mentoring commented on src/main/java/org/store/clothstar/category/controller/CategoryController.java
> +    }
API 응답으로 `MessageDTO`를 사용하여 클라이언트에게 메시지와 생성된 리소스의 위치를 `String` 형태로 반환하는 예시를 아래와 같이 제공할 수 있습니다. 이 방식은 클라이언트에게 추가적인 정보(예: 성공 메시지, 리소스 위치 등)를 제공하고자 할 때 유용합니다.

먼저, `MessageDTO` 클래스를 정의합니다. 이 클래스는 응답 메시지와 생성된 리소스의 URI를 포함합니다.

```java
public class MessageDTO {
    private String message;
    private String location;

    // 생성자, getter, setter 생략
}
```

그런 다음, 컨트롤러에서 `MessageDTO` 인스턴스를 생성하고, 이를 통해 응답 메시지와 생성된 리소스의 URI를 클라이언트에게 반환하는 방식을 구현합니다.

```java
@RestController
@RequiredArgsConstructor
@RequestMapping("/v1/categories")
public class CategoryController {

    private final CategoryService categoryService;

    @PostMapping
    public ResponseEntity<MessageDTO> createCategory(@Validated @RequestBody CreateCategoryRequest createCategoryRequest) {
        Long categoryId = categoryService.createCategory(createCategoryRequest);
        String location = ServletUriComponentsBuilder
            .fromCurrentRequest() // 현재 요청의 URI를 사용
            .path("/{id}") // 경로 변수 추가
            .buildAndExpand(categoryId) // {id} 자리에 실제 categoryId 값을 삽입
            .toUriString(); // 최종 URI를 String 형태로 생성

        MessageDTO messageDTO = new MessageDTO();
        messageDTO.setMessage("카테고리가 성공적으로 생성되었습니다.");
        messageDTO.setLocation(location);

        return ResponseEntity.ok().body(messageDTO); // 200 OK 응답과 함께 MessageDTO 반환
    }
}
```

이 예시에서는 `ResponseEntity.created(location).build()` 대신 `ResponseEntity.ok().body(messageDTO)`를 사용하여 HTTP 상태 코드 `200 OK`와 함께 `MessageDTO` 객체를 반환하고 있습니다. 이 객체는 클라이언트에게 성공 메시지와 함께 생성된 리소스의 정확한 위치(URL)를 문자열 형태로 제공합니다.

이 방식을 사용하면 클라이언트가 추가 정보를 더 쉽게 이해하고 사용할 수 있으며, API의 사용성을 향상시킬 수 있습니다. 다만, 리소스 생성에 대한 일반적인 RESTful 규약은 `201 Created` 상태 코드와 `Location` 헤더를 사용하는 것이므로, 이를 염두에 두고 적절한 상황에서 사용하는 것이 중요합니다.

2024-03-31 00:33 UTC, upswp approved these changes
하위의 리뷰들은 별도의 브랜치를 파서 작업해주세요

2024-03-31 00:33 UTC, upswp commented on src/main/java/org/store/clothstar/product/domain/Product.java
> +    }
Product 하위에 해당하는 ProductOptions들의 id를 알고있다고 가정하고
ids를 통해서 삭제여부를 
- check [ o ]
  - check했을때, 다 삭제 안되있으면 삭제가 안되도록
  - 그렇다면 하위의 options가 삭제가 안된상태라면 어떻게 할 것인지 추가로직 필요
- 직접삭제

2024-03-31 00:33 UTC, upswp commented on src/main/java/org/store/clothstar/product/domain/Product.java
> +    }
하위 객체중에 하나라도 상태값이 진행상태면, 상위 부모의 상태값도 진행이 되도록 설계 되면 좋겠습니다.

2024-03-31 15:25 UTC, hjj4060 approved these changes

2024-04-02 10:44 UTC, merged